environment=dev
service_name=service-b
application_packages=com.example.serviceb
server_url=https://localhost:8200
verify_server_cert=false
transaction_ignore_urls=**/actuator/**,**/v1/catalog/**,**/v1/health/**
use_path_as_transaction_name=true
