environment=dev
service_name=service-a
application_packages=com.example.servicea
server_url=https://localhost:8200
verify_server_cert=false
transaction_ignore_urls=actuator*,catalog*,health*
use_path_as_transaction_name=true
